# Generated by Django 4.1.3 on 2023-05-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nothing', max_length=1000)),
                ('location', models.CharField(default='Nothing', max_length=100)),
                ('min_price', models.IntegerField(default=0)),
                ('max_price', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
