# Generated by Django 4.1.3 on 2023-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restaurant_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tables',
            field=models.IntegerField(default=0),
        ),
    ]
