# Generated by Django 4.1.3 on 2023-05-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
