# Generated by Django 4.1.3 on 2023-05-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_restaurantlocations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='restaurantlocations',
        ),
    ]
